version: "3.9"
services:
  backend:
    image: "alexandrubaltazar/student-management-system:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev