# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - student-management-system

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_033298ce3dde4f31bf51f6ab6b4961a0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ec42530fcaa74b1a857e13af2b200764 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_033298ce3dde4f31bf51f6ab6b4961a0 }}/alexandrubaltazar/student-management-system:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'student-management-system'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_536b1f135b214245833bad57913b9d83 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_033298ce3dde4f31bf51f6ab6b4961a0 }}/alexandrubaltazar/student-management-system:${{ github.sha }}'